/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Meal {
    fat: bigint;
    carbs: bigint;
    calories: bigint;
    name: string;
    protein: bigint;
}
export interface Exercise {
    name: string;
    reps: bigint;
    sets: bigint;
    durationMinutes: bigint;
}
export interface WeeklyMealPlan {
    days: Array<DailyMealPlan>;
}
export interface WeeklyPlan {
    days: Array<WorkoutDay>;
}
export interface DailyMealPlan {
    dessert?: Meal;
    breakfast: Meal;
    lunch: Meal;
    dinner: Meal;
}
export interface Profile {
    age: bigint;
    fitnessLevel: FitnessLevel;
    goal: FitnessGoal;
    name: string;
}
export interface WorkoutDay {
    day: string;
    rest: boolean;
    exercises: Array<Exercise>;
}
export enum FitnessGoal {
    generalFitness = "generalFitness",
    weightLoss = "weightLoss",
    flexibility = "flexibility",
    muscleGain = "muscleGain",
    endurance = "endurance"
}
export enum FitnessLevel {
    intermediate = "intermediate",
    beginner = "beginner",
    advanced = "advanced"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    generateMealPlan(): Promise<WeeklyMealPlan>;
    generateWorkoutPlan(): Promise<WeeklyPlan>;
    getAllProfiles(): Promise<Array<Profile>>;
    getCallerUserProfile(): Promise<Profile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getMealPlan(): Promise<WeeklyMealPlan>;
    getProfile(): Promise<Profile>;
    getUserProfile(user: Principal): Promise<Profile | null>;
    getWorkoutPlan(): Promise<WeeklyPlan>;
    isCallerAdmin(): Promise<boolean>;
    saveCallerUserProfile(profile: Profile): Promise<void>;
    updateProfile(name: string, age: bigint, fitnessLevel: FitnessLevel, goal: FitnessGoal): Promise<void>;
}
import type { DailyMealPlan as _DailyMealPlan, FitnessGoal as _FitnessGoal, FitnessLevel as _FitnessLevel, Meal as _Meal, Profile as _Profile, UserRole as _UserRole, WeeklyMealPlan as _WeeklyMealPlan } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async generateMealPlan(): Promise<WeeklyMealPlan> {
        if (this.processError) {
            try {
                const result = await this.actor.generateMealPlan();
                return from_candid_WeeklyMealPlan_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.generateMealPlan();
            return from_candid_WeeklyMealPlan_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async generateWorkoutPlan(): Promise<WeeklyPlan> {
        if (this.processError) {
            try {
                const result = await this.actor.generateWorkoutPlan();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.generateWorkoutPlan();
            return result;
        }
    }
    async getAllProfiles(): Promise<Array<Profile>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllProfiles();
                return from_candid_vec_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllProfiles();
            return from_candid_vec_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<Profile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMealPlan(): Promise<WeeklyMealPlan> {
        if (this.processError) {
            try {
                const result = await this.actor.getMealPlan();
                return from_candid_WeeklyMealPlan_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMealPlan();
            return from_candid_WeeklyMealPlan_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async getProfile(): Promise<Profile> {
        if (this.processError) {
            try {
                const result = await this.actor.getProfile();
                return from_candid_Profile_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProfile();
            return from_candid_Profile_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<Profile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async getWorkoutPlan(): Promise<WeeklyPlan> {
        if (this.processError) {
            try {
                const result = await this.actor.getWorkoutPlan();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getWorkoutPlan();
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async saveCallerUserProfile(arg0: Profile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(to_candid_Profile_n19(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(to_candid_Profile_n19(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async updateProfile(arg0: string, arg1: bigint, arg2: FitnessLevel, arg3: FitnessGoal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateProfile(arg0, arg1, to_candid_FitnessLevel_n21(this._uploadFile, this._downloadFile, arg2), to_candid_FitnessGoal_n23(this._uploadFile, this._downloadFile, arg3));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateProfile(arg0, arg1, to_candid_FitnessLevel_n21(this._uploadFile, this._downloadFile, arg2), to_candid_FitnessGoal_n23(this._uploadFile, this._downloadFile, arg3));
            return result;
        }
    }
}
function from_candid_DailyMealPlan_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _DailyMealPlan): DailyMealPlan {
    return from_candid_record_n7(_uploadFile, _downloadFile, value);
}
function from_candid_FitnessGoal_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _FitnessGoal): FitnessGoal {
    return from_candid_variant_n15(_uploadFile, _downloadFile, value);
}
function from_candid_FitnessLevel_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _FitnessLevel): FitnessLevel {
    return from_candid_variant_n13(_uploadFile, _downloadFile, value);
}
function from_candid_Profile_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Profile): Profile {
    return from_candid_record_n11(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n18(_uploadFile, _downloadFile, value);
}
function from_candid_WeeklyMealPlan_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _WeeklyMealPlan): WeeklyMealPlan {
    return from_candid_record_n4(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Profile]): Profile | null {
    return value.length === 0 ? null : from_candid_Profile_n10(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Meal]): Meal | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    age: bigint;
    fitnessLevel: _FitnessLevel;
    goal: _FitnessGoal;
    name: string;
}): {
    age: bigint;
    fitnessLevel: FitnessLevel;
    goal: FitnessGoal;
    name: string;
} {
    return {
        age: value.age,
        fitnessLevel: from_candid_FitnessLevel_n12(_uploadFile, _downloadFile, value.fitnessLevel),
        goal: from_candid_FitnessGoal_n14(_uploadFile, _downloadFile, value.goal),
        name: value.name
    };
}
function from_candid_record_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    days: Array<_DailyMealPlan>;
}): {
    days: Array<DailyMealPlan>;
} {
    return {
        days: from_candid_vec_n5(_uploadFile, _downloadFile, value.days)
    };
}
function from_candid_record_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    dessert: [] | [_Meal];
    breakfast: _Meal;
    lunch: _Meal;
    dinner: _Meal;
}): {
    dessert?: Meal;
    breakfast: Meal;
    lunch: Meal;
    dinner: Meal;
} {
    return {
        dessert: record_opt_to_undefined(from_candid_opt_n8(_uploadFile, _downloadFile, value.dessert)),
        breakfast: value.breakfast,
        lunch: value.lunch,
        dinner: value.dinner
    };
}
function from_candid_variant_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    intermediate: null;
} | {
    beginner: null;
} | {
    advanced: null;
}): FitnessLevel {
    return "intermediate" in value ? FitnessLevel.intermediate : "beginner" in value ? FitnessLevel.beginner : "advanced" in value ? FitnessLevel.advanced : value;
}
function from_candid_variant_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    generalFitness: null;
} | {
    weightLoss: null;
} | {
    flexibility: null;
} | {
    muscleGain: null;
} | {
    endurance: null;
}): FitnessGoal {
    return "generalFitness" in value ? FitnessGoal.generalFitness : "weightLoss" in value ? FitnessGoal.weightLoss : "flexibility" in value ? FitnessGoal.flexibility : "muscleGain" in value ? FitnessGoal.muscleGain : "endurance" in value ? FitnessGoal.endurance : value;
}
function from_candid_variant_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_vec_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_DailyMealPlan>): Array<DailyMealPlan> {
    return value.map((x)=>from_candid_DailyMealPlan_n6(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Profile>): Array<Profile> {
    return value.map((x)=>from_candid_Profile_n10(_uploadFile, _downloadFile, x));
}
function to_candid_FitnessGoal_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: FitnessGoal): _FitnessGoal {
    return to_candid_variant_n24(_uploadFile, _downloadFile, value);
}
function to_candid_FitnessLevel_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: FitnessLevel): _FitnessLevel {
    return to_candid_variant_n22(_uploadFile, _downloadFile, value);
}
function to_candid_Profile_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Profile): _Profile {
    return to_candid_record_n20(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_record_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    age: bigint;
    fitnessLevel: FitnessLevel;
    goal: FitnessGoal;
    name: string;
}): {
    age: bigint;
    fitnessLevel: _FitnessLevel;
    goal: _FitnessGoal;
    name: string;
} {
    return {
        age: value.age,
        fitnessLevel: to_candid_FitnessLevel_n21(_uploadFile, _downloadFile, value.fitnessLevel),
        goal: to_candid_FitnessGoal_n23(_uploadFile, _downloadFile, value.goal),
        name: value.name
    };
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: FitnessLevel): {
    intermediate: null;
} | {
    beginner: null;
} | {
    advanced: null;
} {
    return value == FitnessLevel.intermediate ? {
        intermediate: null
    } : value == FitnessLevel.beginner ? {
        beginner: null
    } : value == FitnessLevel.advanced ? {
        advanced: null
    } : value;
}
function to_candid_variant_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: FitnessGoal): {
    generalFitness: null;
} | {
    weightLoss: null;
} | {
    flexibility: null;
} | {
    muscleGain: null;
} | {
    endurance: null;
} {
    return value == FitnessGoal.generalFitness ? {
        generalFitness: null
    } : value == FitnessGoal.weightLoss ? {
        weightLoss: null
    } : value == FitnessGoal.flexibility ? {
        flexibility: null
    } : value == FitnessGoal.muscleGain ? {
        muscleGain: null
    } : value == FitnessGoal.endurance ? {
        endurance: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
