/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface DailyMealPlan {
  'dessert' : [] | [Meal],
  'breakfast' : Meal,
  'lunch' : Meal,
  'dinner' : Meal,
}
export interface Exercise {
  'name' : string,
  'reps' : bigint,
  'sets' : bigint,
  'durationMinutes' : bigint,
}
export type FitnessGoal = { 'generalFitness' : null } |
  { 'weightLoss' : null } |
  { 'flexibility' : null } |
  { 'muscleGain' : null } |
  { 'endurance' : null };
export type FitnessLevel = { 'intermediate' : null } |
  { 'beginner' : null } |
  { 'advanced' : null };
export interface Meal {
  'fat' : bigint,
  'carbs' : bigint,
  'calories' : bigint,
  'name' : string,
  'protein' : bigint,
}
export interface Profile {
  'age' : bigint,
  'fitnessLevel' : FitnessLevel,
  'goal' : FitnessGoal,
  'name' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface WeeklyMealPlan { 'days' : Array<DailyMealPlan> }
export interface WeeklyPlan { 'days' : Array<WorkoutDay> }
export interface WorkoutDay {
  'day' : string,
  'rest' : boolean,
  'exercises' : Array<Exercise>,
}
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'generateMealPlan' : ActorMethod<[], WeeklyMealPlan>,
  'generateWorkoutPlan' : ActorMethod<[], WeeklyPlan>,
  'getAllProfiles' : ActorMethod<[], Array<Profile>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [Profile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getMealPlan' : ActorMethod<[], WeeklyMealPlan>,
  'getProfile' : ActorMethod<[], Profile>,
  'getUserProfile' : ActorMethod<[Principal], [] | [Profile]>,
  'getWorkoutPlan' : ActorMethod<[], WeeklyPlan>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[Profile], undefined>,
  'updateProfile' : ActorMethod<
    [string, bigint, FitnessLevel, FitnessGoal],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];