/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Meal = IDL.Record({
  'fat' : IDL.Nat,
  'carbs' : IDL.Nat,
  'calories' : IDL.Nat,
  'name' : IDL.Text,
  'protein' : IDL.Nat,
});
export const DailyMealPlan = IDL.Record({
  'dessert' : IDL.Opt(Meal),
  'breakfast' : Meal,
  'lunch' : Meal,
  'dinner' : Meal,
});
export const WeeklyMealPlan = IDL.Record({ 'days' : IDL.Vec(DailyMealPlan) });
export const Exercise = IDL.Record({
  'name' : IDL.Text,
  'reps' : IDL.Nat,
  'sets' : IDL.Nat,
  'durationMinutes' : IDL.Nat,
});
export const WorkoutDay = IDL.Record({
  'day' : IDL.Text,
  'rest' : IDL.Bool,
  'exercises' : IDL.Vec(Exercise),
});
export const WeeklyPlan = IDL.Record({ 'days' : IDL.Vec(WorkoutDay) });
export const FitnessLevel = IDL.Variant({
  'intermediate' : IDL.Null,
  'beginner' : IDL.Null,
  'advanced' : IDL.Null,
});
export const FitnessGoal = IDL.Variant({
  'generalFitness' : IDL.Null,
  'weightLoss' : IDL.Null,
  'flexibility' : IDL.Null,
  'muscleGain' : IDL.Null,
  'endurance' : IDL.Null,
});
export const Profile = IDL.Record({
  'age' : IDL.Nat,
  'fitnessLevel' : FitnessLevel,
  'goal' : FitnessGoal,
  'name' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'generateMealPlan' : IDL.Func([], [WeeklyMealPlan], []),
  'generateWorkoutPlan' : IDL.Func([], [WeeklyPlan], []),
  'getAllProfiles' : IDL.Func([], [IDL.Vec(Profile)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(Profile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getMealPlan' : IDL.Func([], [WeeklyMealPlan], ['query']),
  'getProfile' : IDL.Func([], [Profile], ['query']),
  'getUserProfile' : IDL.Func([IDL.Principal], [IDL.Opt(Profile)], ['query']),
  'getWorkoutPlan' : IDL.Func([], [WeeklyPlan], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([Profile], [], []),
  'updateProfile' : IDL.Func(
      [IDL.Text, IDL.Nat, FitnessLevel, FitnessGoal],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Meal = IDL.Record({
    'fat' : IDL.Nat,
    'carbs' : IDL.Nat,
    'calories' : IDL.Nat,
    'name' : IDL.Text,
    'protein' : IDL.Nat,
  });
  const DailyMealPlan = IDL.Record({
    'dessert' : IDL.Opt(Meal),
    'breakfast' : Meal,
    'lunch' : Meal,
    'dinner' : Meal,
  });
  const WeeklyMealPlan = IDL.Record({ 'days' : IDL.Vec(DailyMealPlan) });
  const Exercise = IDL.Record({
    'name' : IDL.Text,
    'reps' : IDL.Nat,
    'sets' : IDL.Nat,
    'durationMinutes' : IDL.Nat,
  });
  const WorkoutDay = IDL.Record({
    'day' : IDL.Text,
    'rest' : IDL.Bool,
    'exercises' : IDL.Vec(Exercise),
  });
  const WeeklyPlan = IDL.Record({ 'days' : IDL.Vec(WorkoutDay) });
  const FitnessLevel = IDL.Variant({
    'intermediate' : IDL.Null,
    'beginner' : IDL.Null,
    'advanced' : IDL.Null,
  });
  const FitnessGoal = IDL.Variant({
    'generalFitness' : IDL.Null,
    'weightLoss' : IDL.Null,
    'flexibility' : IDL.Null,
    'muscleGain' : IDL.Null,
    'endurance' : IDL.Null,
  });
  const Profile = IDL.Record({
    'age' : IDL.Nat,
    'fitnessLevel' : FitnessLevel,
    'goal' : FitnessGoal,
    'name' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'generateMealPlan' : IDL.Func([], [WeeklyMealPlan], []),
    'generateWorkoutPlan' : IDL.Func([], [WeeklyPlan], []),
    'getAllProfiles' : IDL.Func([], [IDL.Vec(Profile)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(Profile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getMealPlan' : IDL.Func([], [WeeklyMealPlan], ['query']),
    'getProfile' : IDL.Func([], [Profile], ['query']),
    'getUserProfile' : IDL.Func([IDL.Principal], [IDL.Opt(Profile)], ['query']),
    'getWorkoutPlan' : IDL.Func([], [WeeklyPlan], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([Profile], [], []),
    'updateProfile' : IDL.Func(
        [IDL.Text, IDL.Nat, FitnessLevel, FitnessGoal],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };